#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-disposable
Version  : 0.0.9
Release  : 8
URL      : https://rubygems.org/downloads/disposable-0.0.9.gem
Source0  : https://rubygems.org/downloads/disposable-0.0.9.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-uber

%description
# Disposable
_Decorators on top of your ORM layer._
## Introduction
Disposable gives you "_Twins_" which are domain objects, decoupled from ActiveRecord, DataMapper or whatever ORM you use.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n disposable-0.0.9
gem spec %{SOURCE0} -l --ruby > rubygem-disposable.gemspec

%build
gem build rubygem-disposable.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
disposable-0.0.9.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/disposable-0.0.9
ruby -v -I.:lib:test test*/test_*.rb
ruby -v -I.:lib:test test*/*_test.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/disposable-0.0.9.gem
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/CHANGES.md
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/README.md
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/STUFF
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/database.sqlite3
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/disposable.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/gemfiles/Gemfile.rails-2.3
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/gemfiles/Gemfile.rails-2.3.lock
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/gemfiles/Gemfile.rails-3.0
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/gemfiles/Gemfile.rails-3.0.lock
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/gemfiles/Gemfile.rails-3.2
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/gemfiles/Gemfile.rails-3.2.lock
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/gemfiles/Gemfile.rails-4.0
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/gemfiles/Gemfile.rails-4.0.lock
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/gemfiles/Gemfile.rails-4.1
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/gemfiles/Gemfile.rails-4.1.lock
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/lib/disposable.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/lib/disposable/composition.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/lib/disposable/twin.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/lib/disposable/twin/builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/lib/disposable/twin/composition.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/lib/disposable/twin/finders.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/lib/disposable/twin/new.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/lib/disposable/twin/option.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/lib/disposable/twin/representer.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/lib/disposable/twin/save.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/lib/disposable/twin/save_.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/lib/disposable/twin/struct.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/lib/disposable/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/test/composition_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/test/twin/composition_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/disposable-0.0.9/test/twin/twin_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/disposable-0.0.9.gemspec
